plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
    maven {
        name = 'Create Maven'
        url = 'https://maven.createmod.net'
    }
    maven {
        name = 'Registrate Snapshots'
        url = 'https://maven.ithundxr.dev/snapshots'
    }
    maven {
        name = 'CurseMaven'
        url = 'https://cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
    maven {
        name = 'BlameJared Maven'
        url = 'https://maven.blamejared.com'
    }
}

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').absolutePath, '--existing', file('src/main/resources/').absolutePath
        }
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

dependencies {
    implementation("curse.maven:create-328085:7963363")
    implementation("com.tterrag.registrate:Registrate:${project.registrate_version}")
    implementation("net.createmod.ponder:ponder-neoforge:${project.ponder_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-1.21.1:${project.flywheel_version}")
    compileOnly("mezz.jei:jei-1.21.1-neoforge-api:19.21.0.246")
    runtimeOnly("mezz.jei:jei-1.21.1-neoforge:19.21.0.246")
}
