mod_id = create_reclamation
mod_name = Create: Reclamation
mod_license = MIT
mod_version = 0.1.0
mod_group_id = com.reclamation
mod_authors = Antigravity

minecraft_version = 1.21.1
neo_version = 21.1.251
neo_version_range = [21.1.219,)
loader_version_range = [4,)

create_version = 6.0.10
create_version_range = [6.0.10,6.1.0)

ponder_version = 1.0.87+mc1.21.1
flywheel_version = 1.0.0-beta-4
registrate_version = MC1.21-1.3.0+67
